[package]
name = "graphql-cached-parser-performance-test"
version = "0.1.0"
authors = ["jsus <esseswann@gmail.com>"]
edition = "2018"

[dependencies]
graphql-parser = "0.3.0"
fasthash = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "performance"
harness = false